jobs:
  - name: vote_be_runCI
    type: runCI
    steps:
      - OUT: vote_be

  - name: vote_fe_runCI
    type: runCI
    steps:
      - OUT: vote_fe

  - name: vote-fe-temp
    type: manifest
    steps:
      - IN: vote_fe
      - TASK: managed

  - name: vote-be-temp
    type: manifest
    steps:
      - IN: vote_be
      - TASK: managed

  - name: deploy-test-vote-app
    type: deploy
    method: replace
    steps:
      - IN: vote-be-temp
      - IN: vote-fe-temp
      - IN: gke_cluster
      - IN: test_fe_options
        applyTo:
          - vote-fe-temp
      - IN: test_be_options
        applyTo:
          - vote-be-temp

  - name: prov_test_lb
    type: provision
    steps:
      - IN: test_be_lb
      - IN: test_fe_lb
      - IN: deploy-test-vote-app
        switch: off

  - name: prov_prod_lb
    type: provision
    steps:
      - IN: prod_be_lb
      - IN: prod_fe_lb

  - name: rel_prod
    type: release
    bump: minor
    steps:
      - IN: prod_sem_ver
      - IN: deploy-test-vote-app
        switch: off

  - name: deploy-prod-vote-app
    type: deploy
    method: replace
    steps:
      - IN: rel_prod
      - IN: gke_cluster
      - IN: prod_fe_options
        applyTo:
          - vote-fe-temp
      - IN: prod_be_options
        applyTo:
          - vote-be-temp